blog/urls.py
from django.contrib import admin
from django.urls import path
from blog.views import *


app_name = 'blog'

urlpatterns = [
    path('', news_view, name='news'),
    path('post-<int:pid>', single_view, name='single'),
    path('archive/<int:published_month>', archive_view, name='archive'),
    path('author/<str:author_username>', news_view, name='author'),
    path('search/', blog_search, name='search'),
    path('tags/<str:tag_name>', news_view, name='tag'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    'static':StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('news/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.conftrib.sitemaps.views.sitemap'),
    path('summernote/', include('django_summernote.urls')),

]
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class Post(models.Model):
    image= models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    tags = TaggableManager()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True)


    class Meta:
        ordering=('-created_date',)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid':self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

blog/forms.py
from django import forms
from blog.models import Comment


from website.models import Contact, Newsletter


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['post','name', 'email', 'subject', 'message']

blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import Post, Comment
from blog.forms import CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages

# Create your views here.

def news_view(request, author_username=None, **kwargs):
    posts= Post.objects.filter(status=True)
    if author_username is not None:
        posts= posts.filter(author__username=author_username)
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
    posts = Paginator(posts,3)
    page_number = request.GET.get('page')
    try:
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.page(1)
    except EmptyPage:
        posts = posts.page(posts.num_pages)
    context={'posts': posts}
    return render(request, 'blog/news.html',context)

def single_view(request,pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your comment have been submitted Successfully')
        else:
            messages.add_message(request, messages.ERROR, 'Your comment did not submitted.')   
    post=get_object_or_404(Post, id=pid, status=1)
    comments = Comment.objects.filter(post=post.id, approved=True).order_by('-created_date')
    form = CommentForm()
    context={'post': post, 'comments': comments, 'form': form}
    return render(request, 'blog/single-news.html',context)


def archive_view(request, published_month):
    posts=Post.objects.filter(status=True, published_date__month=published_month)
    context={'posts': posts}
    return render(request, 'blog/news.html',context)

def blog_search(request):
    posts= Post.objects.filter(status=True)
    if request.method == 'GET':
        posts=posts.filter(content__contains=request.GET.get('s'))
    context={'posts': posts}
    return render(request, 'blog/news.html',context)

templates/blog/archive-news.html
<div class="archive-posts">
    <h4>Archive Posts</h4>
    <ul>
        {% for name,count in month_posts.items %}
        {% if count.0 != 0 %}
        <li><a href="{% url 'blog:archive' published_month=count.1 %}">{{name}} ({{count.0}})</a></li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

templates/blog/blog-search.html
<div class="search-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <span class="close-btn"><i class="fas fa-window-close"></i></span>
                <div class="search-bar">
                    <form class="search-bar-tablecell" action="{% url 'blog:search' %}">
                        <h3>Search For:</h3>
                        <input type="text" name="s" placeholder="Keywords">
                        <button type="submit">Search <i class="fas fa-search"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/blog/blog-tags.html
<div class="tag-section">
    <h4>Tags</h4>
    <ul>
        {% for tag in post.tags.all %}
        <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
        {% endfor %}
    </ul>
</div>

templates/blog/news.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<!-- search area -->
{% include 'blog/blog-search.html' %}
	<!-- end search arewa -->
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Organic Information</p>
						<h1>News Article</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- latest news -->
	<div class="latest-news mt-150 mb-150">
		<div class="container">
			<div class="row">
				{% for post in posts %}
				<div class="col-lg-4 col-md-6">
					<div class="single-latest-news">
						<a href="{% url 'blog:single' pid=post.id %}"><img src="{{ post.image.url }}" alt=""></a>
						<div class="news-text-box">
							<h3><a href="{% url 'blog:single' pid=post.id %}">{{ post.title }}</a></h3>
							<p class="blog-meta">
								<span class="author"><i class="fas fa-user"></i> <a href="{% url 'blog:author' author_username=post.author.username %}">{{ post.author.get_full_name }}</a></span>
								<span class="date"><i class="fas fa-calendar"></i> {{ post.published_date|date:"D d M Y" }}</span>
							</p>
							<p class="excerpt">{{ post.content|truncatewords:20 }}</p>
							<a href="{% url 'blog:single' pid=post.id %}" class="read-more-btn">read more <i class="fas fa-angle-right"></i></a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>

			<div class="row">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 text-center">
							<div class="pagination-wrap">
								<ul>
									{% if posts.has_previous %}
									<li><a href="?page={{ posts.previous_page_number }}">Prev</a></li>
									{% endif %}
									{% for i in posts.paginator.page_range %}
									{% if posts.number == i %}
									<li><a href="?page={{i}}" class="active">{{i}}</a></li>
									{% else %}
									<li><a href="?page={{i}}">{{i}}</a></li>
									{% endif %}
									{% endfor %}
									{% if posts.has_next %}
									<li><a href="?page={{ posts.next_page_number }}">Next</a></li>
									{% endif %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end latest news -->

	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/1.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/2.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/3.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/4.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/5.png' %}" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->

	{% endblock %}

templates/blog/recent-news.html
{% load static %}
<div class="recent-posts">
    <h4>Recent Posts</h4>
    <ul>
        {% for post in posts %}
        <li><a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></li>
        {% endfor %}
    </ul>
</div>

templates/blog/single-news.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}

	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search arewa -->
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Read the Details</p>
						<h1>{{ post.title }}</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->
	
	<!-- single article section -->
	<div class="mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8">
					<div class="single-article-section">
						<div class="single-article-text">
							<img src="{{ post.image.url }}" alt="">
							<p class="blog-meta">
								<span class="author"><i class="fas fa-user"></i>{{ post.author.get_full_name }}</span>
								<span class="date"><i class="fas fa-calendar"></i>{{ post.published_date|date:"D d M Y" }}</span>
							</p>
							<h2>{{ post.title }}</h2>
							<p>{{ post.content|safe }}</p>
						</div>

						<div class="comments-list-wrap">
							<h3 class="comment-count-title">{{comments|length}} Comments</h3>
							{% for comment in comments %}
							<div class="comment-list">
								<div class="single-comment-body">
									<div class="comment-user-avater">
										<img src="{% static 'assets/img/avaters/avatar2.png' %}" alt="">
									</div>
									<div class="comment-text-body">
										<h4>{{comment.name}} <span class="comment-date">{{comment.created_date|date:"d M Y"}}</span></h4>
										<p>{{comment.message}}</p>
									</div>
								</div>
							</div>
							{% empty %}
							<p> No comments yet.</p>
							{% endfor %}

						</div>

						<div class="comment-template">
							<h4>Leave a comment</h4>
							<p>If you have a comment dont feel hesitate to send us your opinion.</p>
							<form method="post" action="{% url 'blog:single' pid=post.id %}">
								{% csrf_token %}
								<input type="hidden" name="post" value="{{post.id}}">
								<p>
									<input type="text" name="name" placeholder="Your Name">
									<input type="email" name="email"placeholder="Your Email">
								</p>
								<p><input type="text" name="subject" placeholder="Subject"></p>
								<p><textarea name="message" cols="30" rows="10" placeholder="Your Message"></textarea></p>
								<p><input type="submit" value="Submit"></p>
							</form>
						</div>
						<p></p>
						{% if messages %}
						{% for message in messages %}
						  <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
						{% endfor %}
						 {% endif %}
  
						  {% if form.errors %}
						<div class="alert alert-error">
						   <h4>Please fix the following errors</h4>
							 <ul>
							{% for field in form %}
							   {% if field.errors %}
							 {% for error in field.errors %}
						   <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
						 {% endfor %}
						{% endif %}
					 {% endfor %}
						 </ul>
					   {% if form.non_field_errors %}
					   {{ form.non_field_errors }}
						{% endif %}
					   </div>
						{% endif %}
					</div>
				</div>
				<div class="col-lg-4">
					<div class="sidebar-section">
						{% recent_posts %}
						{% archive %}
						{% include 'blog/blog-tags.html' %}
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end single article section -->

	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/1.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/2.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/3.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/4.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/5.png' %}" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->

	{% endblock %}