accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    #login
    path('login/', views.login_view, name='login'),
    #logout
    path('logout', views.logout_view, name='logout'),
    #registeration
    path('signup', views.signup_view, name='signup'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog.views import *


app_name = 'blog'

urlpatterns = [
    path('', news_view, name='news'),
    path('post-<int:pid>', single_view, name='single'),
    path('archive/<int:published_month>', archive_view, name='archive'),
    path('author/<str:author_username>', news_view, name='author'),
    path('search/', blog_search, name='search'),
    path('tags/<str:tag_name>', news_view, name='tag'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    'static':StaticViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('news/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.conftrib.sitemaps.views.sitemap'),
    path('summernote/', include('django_summernote.urls')),

]
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.contrib import admin
from django.urls import path
from website.views import *


app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    path('newsletter/', newsletter_view, name='newsletter'),
]

templates/base.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Contact</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	{% compress css %}
	<link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
	<!-- animate css -->
	<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{% static 'assets/css/meanmenu.min.css' %}">
	<!-- main style -->
	<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
	<!-- responsive -->
	<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
	{% endcompress %}
</head>
<body>
	
	<!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="{% url 'website:index' %}">
								<img src="{% static 'assets/img/logo.png' %}" alt="">
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item"><a href="{% url 'website:index' %}">Home</a>
								</li>
								<li><a href="{% url 'website:about' %}">About</a></li>
								<li><a href="{% url 'blog:news' %}">News</a>
								</li>
								<li><a href="{% url 'website:contact' %}">Contact</a></li>
								<li>
									<div class="header-icons">
										<ul>
										{% if request.user.is_authenticated %}
										<ul>
										<li><a> Logged in as {{request.user.username}}</a></li>
										<li><a href="{% url 'accounts:logout' %}">Logout</a></li>
										</ul>
										{% else %}
										<li><a href="{% url 'accounts:login' %}">Login</a></li>
										<li><a href="{% url 'accounts:signup' %}">Signup</a></li>
										{% endif %}
									     </ul>
									</div>
								</li>
							</ul>
						</nav>
						<a class="mobile-show search-bar-icon" href=""><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div>
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>

    {% block content %}

    {% endblock %}




	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">About us</h2>
						<p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Get in Touch</h2>
						<ul>
							<li>34/8, East Hukupara, Gifirtok, Sadan.</li>
							<li>support@fruitkha.com</li>
							<li>+00 111 222 3333</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box pages">
						<h2 class="widget-title">Pages</h2>
						<ul>
							<li><a href="{% url 'website:index' %}">Home</a></li>
							<li><a href="{% url 'website:about' %}">About</a></li>
							<li><a href="{% url 'blog:news' %}">News</a></li>
							<li><a href="{% url 'website:contact' %}">Contact</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">Subscribe</h2>
						<p>Subscribe to our mailing list to get the latest updates.</p>
						<form action="{% url 'website:newsletter' %}" method="post">
							{% csrf_token %}
							<input type="email" name="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->
	
	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<p>Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>,  All Rights Reserved.</p>
				</div>
				<div class="col-lg-6 text-right col-md-12">
					<div class="social-icons">
						<ul>
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end copyright -->
	
	<!-- jquery -->
	{% compress js %}
	<script src="{% static 'assets/js/jquery-1.11.3.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
	<!-- count down -->
	<script src="{% static 'assets/js/jquery.countdown.js' %}"></script>
	<!-- isotope -->
	<script src="{% static 'assets/js/jquery.isotope-3.0.6.min.js' %}"></script>
	<!-- waypoints -->
	<script src="{% static 'assets/js/waypoints.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
	<!-- magnific popup -->
	<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
	<!-- mean menu -->
	<script src="{% static 'assets/js/jquery.meanmenu.min.js' %}"></script>
	<!-- sticker js -->
	<script src="{% static 'assets/js/sticker.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'assets/js/main.js' %}"></script>
	{% endcompress %}

</body>
</html>

templates/comming-soon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Will be available soon</h1>
    
</body>
</html>